# Generated by Django 4.2.21 on 2025-05-28 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('greeting', 'Greeting'), ('vehicle_info', 'Vehicle Information'), ('tire_specs', 'Tire Specifications'), ('product_info', 'Product Information'), ('confirmation', 'Confirmation'), ('farewell', 'Farewell')], max_length=20)),
                ('next_state', models.CharField(blank=True, choices=[('greeting', 'Greeting'), ('vehicle_info', 'Vehicle Information'), ('tire_specs', 'Tire Specifications'), ('product_info', 'Product Information'), ('confirmation', 'Confirmation'), ('farewell', 'Farewell')], max_length=20, null=True)),
                ('required_info', models.JSONField(blank=True, default=dict)),
                ('collected_info', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlowTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_state', models.CharField(choices=[('greeting', 'Greeting'), ('vehicle_info', 'Vehicle Information'), ('tire_specs', 'Tire Specifications'), ('product_info', 'Product Information'), ('confirmation', 'Confirmation'), ('farewell', 'Farewell')], max_length=20)),
                ('next_state', models.CharField(choices=[('greeting', 'Greeting'), ('vehicle_info', 'Vehicle Information'), ('tire_specs', 'Tire Specifications'), ('product_info', 'Product Information'), ('confirmation', 'Confirmation'), ('farewell', 'Farewell')], max_length=20)),
                ('trigger_pattern', models.CharField(max_length=255)),
                ('response', models.TextField()),
                ('required_info', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='conversation_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.conversationstate'),
        ),
    ]
