# Generated by Django 4.2.21 on 2025-05-28 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_conversationstate_flowtransition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationstate',
            name='default_next_state',
            field=models.CharField(blank=True, choices=[('greeting', 'Greeting'), ('ask_for_store', 'Asking for Store'), ('ask_for_size_or_vehicle', 'Asking for Size or Vehicle'), ('ask_for_size', 'Asking for Size'), ('ask_for_vehicle', 'Asking for Vehicle'), ('provide_options', 'Providing Options'), ('price_sensitive', 'Price Sensitive Path'), ('quality_brand_focused', 'Quality/Brand Focused Path'), ('brand_sensitive', 'Brand Sensitive Path'), ('confirm_installation', 'Confirming Installation'), ('schedule_appointment', 'Scheduling Appointment'), ('ask_about_saturday', 'Asking about Saturday'), ('ask_about_discount', 'Asking about Discount'), ('start_ticket', 'Starting Ticket'), ('confirmation', 'Confirmation'), ('farewell', 'Farewell'), ('contact_other', 'Contact Other')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='conversationstate',
            name='default_response',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='conversationstate',
            name='next_state',
            field=models.CharField(blank=True, choices=[('greeting', 'Greeting'), ('ask_for_store', 'Asking for Store'), ('ask_for_size_or_vehicle', 'Asking for Size or Vehicle'), ('ask_for_size', 'Asking for Size'), ('ask_for_vehicle', 'Asking for Vehicle'), ('provide_options', 'Providing Options'), ('price_sensitive', 'Price Sensitive Path'), ('quality_brand_focused', 'Quality/Brand Focused Path'), ('brand_sensitive', 'Brand Sensitive Path'), ('confirm_installation', 'Confirming Installation'), ('schedule_appointment', 'Scheduling Appointment'), ('ask_about_saturday', 'Asking about Saturday'), ('ask_about_discount', 'Asking about Discount'), ('start_ticket', 'Starting Ticket'), ('confirmation', 'Confirmation'), ('farewell', 'Farewell'), ('contact_other', 'Contact Other')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='conversationstate',
            name='state',
            field=models.CharField(choices=[('greeting', 'Greeting'), ('ask_for_store', 'Asking for Store'), ('ask_for_size_or_vehicle', 'Asking for Size or Vehicle'), ('ask_for_size', 'Asking for Size'), ('ask_for_vehicle', 'Asking for Vehicle'), ('provide_options', 'Providing Options'), ('price_sensitive', 'Price Sensitive Path'), ('quality_brand_focused', 'Quality/Brand Focused Path'), ('brand_sensitive', 'Brand Sensitive Path'), ('confirm_installation', 'Confirming Installation'), ('schedule_appointment', 'Scheduling Appointment'), ('ask_about_saturday', 'Asking about Saturday'), ('ask_about_discount', 'Asking about Discount'), ('start_ticket', 'Starting Ticket'), ('confirmation', 'Confirmation'), ('farewell', 'Farewell'), ('contact_other', 'Contact Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='flowtransition',
            name='current_state',
            field=models.CharField(choices=[('greeting', 'Greeting'), ('ask_for_store', 'Asking for Store'), ('ask_for_size_or_vehicle', 'Asking for Size or Vehicle'), ('ask_for_size', 'Asking for Size'), ('ask_for_vehicle', 'Asking for Vehicle'), ('provide_options', 'Providing Options'), ('price_sensitive', 'Price Sensitive Path'), ('quality_brand_focused', 'Quality/Brand Focused Path'), ('brand_sensitive', 'Brand Sensitive Path'), ('confirm_installation', 'Confirming Installation'), ('schedule_appointment', 'Scheduling Appointment'), ('ask_about_saturday', 'Asking about Saturday'), ('ask_about_discount', 'Asking about Discount'), ('start_ticket', 'Starting Ticket'), ('confirmation', 'Confirmation'), ('farewell', 'Farewell'), ('contact_other', 'Contact Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='flowtransition',
            name='next_state',
            field=models.CharField(choices=[('greeting', 'Greeting'), ('ask_for_store', 'Asking for Store'), ('ask_for_size_or_vehicle', 'Asking for Size or Vehicle'), ('ask_for_size', 'Asking for Size'), ('ask_for_vehicle', 'Asking for Vehicle'), ('provide_options', 'Providing Options'), ('price_sensitive', 'Price Sensitive Path'), ('quality_brand_focused', 'Quality/Brand Focused Path'), ('brand_sensitive', 'Brand Sensitive Path'), ('confirm_installation', 'Confirming Installation'), ('schedule_appointment', 'Scheduling Appointment'), ('ask_about_saturday', 'Asking about Saturday'), ('ask_about_discount', 'Asking about Discount'), ('start_ticket', 'Starting Ticket'), ('confirmation', 'Confirmation'), ('farewell', 'Farewell'), ('contact_other', 'Contact Other')], max_length=30),
        ),
    ]
