# Generated by Django 4.2.21 on 2025-05-28 19:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_conversationstate_default_next_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowtransition',
            name='required_info',
        ),
        migrations.RemoveField(
            model_name='flowtransition',
            name='response',
        ),
        migrations.AddField(
            model_name='flowtransition',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='flowtransition',
            name='trigger_pattern',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('make', models.CharField(max_length=100)),
                ('services', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('make', 'name')},
            },
        ),
    ]
